CREATE DATABASE CLASES;
GO

USE CLASES;
GO

CREATE TABLE UserRoles(
	UserRoleId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Code NVARCHAR(10) NOT NULL UNIQUE,
	ShowName NVARCHAR(100) NOT NULL,
	CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Users (
	UserId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	RoleId INT NOT NULL REFERENCES UserRoles (UserRoleId),
	UserName NVARCHAR(100) NOT NULL,
	UserAge INT NOT NULL,
	UserMail NVARCHAR(50) NOT NULL,
	UserPhone  NVARCHAR(13) NOT NULL,
	UserNi  NVARCHAR(13) NOT NULL,
	CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE ModuleType(
	ModuleTypeId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	ModuleTypeName NVARCHAR(100) NOT NULL,
	ModuleTypeTech NVARCHAR(100) NOT NULL
);

CREATE TABLE Module (
	ModuleId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	ModuleName NVARCHAR(100) NOT NULL,
	TeacherId UNIQUEIDENTIFIER NOT NULL REFERENCES Users (UserId),
	TypeId INT NOT NULL REFERENCES ModuleType (ModuleTypeId)
);


CREATE TABLE Participation (
	ParticipationId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	StudentId UNIQUEIDENTIFIER NOT NULL REFERENCES Users (UserId),
	ModuleId INT NOT NULL REFERENCES Module (ModuleId),
	Points INT NULL,
	CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
